sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - LEGACY_DEPS="phpunit/phpunit"

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
    - php: 5.6
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^2.2 zendframework/zend-expressive-router:^1.3.2"
    - php: 5.6
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^3.0.1"
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CS_CHECK=true
    - php: 7
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^2.2 zendframework/zend-expressive-router:^1.3.2"
    - php: 7
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^3.0.1"
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^2.2 zendframework/zend-expressive-router:^1.3.2"
    - php: 7.1
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^3.0.1"
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^2.2 zendframework/zend-expressive-router:^1.3.2"
    - php: hhvm
      env:
        - DEPS=locked
        - HELPER_DEPS="zendframework/zend-expressive-helpers:^3.0.1"
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $HELPER_DEPS != '' ]]; then travis_retry composer require $COMPOSER_ARGS --update-with-dependencies $HELPER_DEPS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  slack:
    secure: "e6NSTxYfduEBE4M4ywNmlzWSA1WP/dl5KAsjkQZjKAQMYKNZZ4H6amNF3fyfoq9m8z/oozJYCGPzHwVAnOkK2dr8m3Kv9dfk6T8EeB9o55uBEevwlnqIX48Ls+IKI1ZbTu1+hrUkDRGhIRoEdzDXQR0iBD7bE1TyRvWCoaBTyH4XhOboDJEC+ohVC3TO/uAtvrwpCuZ6U1blUeh+XNy79TrWVoO0erQc/UdNcee8688iUqNHGN7Ds35x/vYuvZnNWrqVH0nW6SUst4KQwFMV25X8LuPd6ZU4NhCog2Q5kZoq+Dw/o7Umdn3qqnjT9sgcDIwdEtb2LYr66nM4fdRe/ueH7EgxSd0x6bBDdSccgj7dNytTD8wh70gLmiKxOK5oomBtVb6XF3dmVzRtY/GMzAXjg7SMWDrqxXU7VXBovENz/nS3AWW+2hOIazkbumq1oDXA/KSFgMEOG40yfRHohOkB0h9CQOypPmnm7G5T4Dn3Zwvkqltrz4YFTtSUflgxl97OQsnwJdCUY7NxZusY4vrrlqGzFvwago5kpFRbBzONaHh5qmIX9KKeCDiITjIV5UO9yZLSQyZCR74THn0TJ2CfcCnW4vKbOHAPVgZRd/XS5JxvxAxN6kozl+4YC33ZJEDSlWMS4C7AxJ0MR/Vu4o93rQxAMqJ1L1Y56adEeBw="
  irc: "irc.freenode.org#zftalk.dev"
  email: false
